Updated cheats

diff --git a/bin/cheat b/bin/cheat
--- a/bin/cheat
+++ b/bin/cheat
@@ -1,24 +1,32 @@
 #!/bin/sh
 
-CHEAT_DIR="$HOME/.config/cheat"
+: "${CHEAT_DIR:=$HOME/.config/cheat}"
+
 USAGE="
  cheat          List available cheats
  cheat app      Print cheat for app
  cheat -e app   Edit cheat for app using EDITOR variable
 "
 
-case $1 in
-   -h|--help) echo "$USAGE" ; exit;;
-   "") ls $CHEAT_DIR ; exit;;
-   -e)
-      [ "$EDITOR" ] || { echo "Please define EDITOR variable in your shell."; exit 1; }
-      [ ! -d "$CHEAT_DIR" ] && mkdir -p $CHEAT_DIR
-      $EDITOR $CHEAT_DIR/$2
-      echo "$CHEAT_DIR/$2"
-      ;;
-   *)
-      [ -f "$CHEAT_DIR/$1" ] || { echo "Could not find '$1' cheatsheet!"; exit 1; }
-      less "$CHEAT_DIR/$1"
-      echo
-esac
+# No args = list available cheat
+[ "$1" ] || { ls $CHEAT_DIR ; exit; }
+op=show
+while [ "$1" ]; do
+   case "$1" in
+      -h|--help) echo "$USAGE" ; exit ;;
+      -e) op=edit ;;
+      *) file="$1" ;;
+   esac
+   shift
+done
+
+if [ "$op" = "edit" ]; then
+   [ ! -d "$CHEAT_DIR" ] && mkdir -p $CHEAT_DIR
+   ${EDITOR:-vi} $CHEAT_DIR/$file
+   echo "$CHEAT_DIR/$file"
+else
+   [ -f "$CHEAT_DIR/$file" ] || { echo "Could not find '$file' cheatsheet!"; exit 1; }
+   less "$CHEAT_DIR/$file"
+   echo
+fi
 
